completed express-post-json - Jonathan Chiang
J0N-C/m2-0921-code-solutions pull request #30
Opened 2021-11-17 05:12 UTC by J0N-C

![express-post-json-before](https://user-images.githubusercontent.com/64382900/142138458-e54d1e27-df73-4eb4-813e-cb2fa00db5bd.JPG)
![express-post-json-after-1](https://user-images.githubusercontent.com/64382900/142138466-36560d6b-32ac-4c53-9ea9-088e90dabffd.JPG)
![express-post-json-after-2](https://user-images.githubusercontent.com/64382900/142138476-651e9271-6898-4270-8d75-c98686bdbe55.JPG)

2021-11-17 05:14 UTC, TimelikeClosure requested changes

2021-11-17 05:14 UTC, TimelikeClosure commented on express-post-json/index.js
> +  res.sendStatus(201);
Don't forget to send a copy of the newly-created grade back to the client:

---

![image](https://user-images.githubusercontent.com/16143771/142139023-4acde00d-68dc-4c76-80dc-039d3173729c.png)

2021-11-18 03:16 UTC, J0N-C commented
![express-post-json-rev-send](https://user-images.githubusercontent.com/64382900/142345370-82587576-d940-4812-9baa-8316a0f3f89a.JPG)

2021-11-18 17:35 UTC, TimelikeClosure approved these changes

2021-11-19 02:53 UTC, merged