Completed express notes api - Jonathan Chiang
J0N-C/m2-0921-code-solutions pull request #31
Opened 2021-11-24 04:08 UTC by J0N-C

GET testing:
![express-notes-api-get-all](https://user-images.githubusercontent.com/64382900/143172686-d271314e-53f2-40de-ab05-405d27965d98.gif)

POST testing:
![express-notes-api-post-all](https://user-images.githubusercontent.com/64382900/143172713-30c3379a-d39a-44bb-a949-fc2c6f74b5fd.gif)

POST intentional 500 error:
![express-notes-api-post-500error](https://user-images.githubusercontent.com/64382900/143172871-f16b0b1d-5494-4ae1-8785-632c1d88811e.JPG)

DELETE testing:
![express-notes-api-delete-all](https://user-images.githubusercontent.com/64382900/143172724-a2003b9e-254e-47df-9922-efbef8e73936.gif)

DELETE intentional 500 error:
![express-notes-api-delete-500](https://user-images.githubusercontent.com/64382900/143173107-41fd2fad-a197-4b8b-8aea-673beee8f302.JPG)

PUT testing:
![express-notes-api-put-all](https://user-images.githubusercontent.com/64382900/143172798-d215e600-ee2d-4dc1-a266-a05483ea17f2.gif)

PUT intentional 500 error:
![express-notes-api-put-500](https://user-images.githubusercontent.com/64382900/143173151-06152a20-16f7-499d-8df0-3d8d89c5ecb8.JPG)

2021-11-24 04:23 UTC, TimelikeClosure requested changes

2021-11-24 04:23 UTC, TimelikeClosure commented on express-notes-api/index.js
> +  }
These routes should always send a `400 Bad Request` if `id` isn't a positive integer:

---

![image](https://user-images.githubusercontent.com/16143771/143174424-f4651e2f-8ac1-4c8b-a2cf-331c65c23b9c.png)

---

![image](https://user-images.githubusercontent.com/16143771/143174436-934bec0f-a003-4749-9a4e-196df4856b36.png)

2021-11-24 04:23 UTC, TimelikeClosure commented on express-notes-api/index.js
> +      res.status(201).send(obj.notes[idNum]);
The `201 Created` status code is only for creating new notes, not updating existing ones:

---

![image](https://user-images.githubusercontent.com/16143771/143174666-5eecfbc1-7916-4581-868a-02f498c83276.png)

2021-11-24 05:24 UTC, J0N-C commented
![express-notes-api-revision-intcheck-putstatusnum](https://user-images.githubusercontent.com/64382900/143179741-3dfe6953-fd5a-4e64-82ef-c742f0ece8f0.gif)

2021-11-25 00:49 UTC, TimelikeClosure approved these changes

2021-11-25 05:03 UTC, merged